spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 20
      minimum-idle: 10
      idle-timeout: 30000
      max-lifetime: 1800000
      connection-timeout: 30000
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        default_schema: hitpixel
        enable_lazy_load_no_trans: true
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/changelog.xml
    default-schema: hitpixel
    driver-class-name: org.postgresql.Driver

hitpixel:
  jwt:
    expires-in-seconds: 3600
    signing-key: ${JWT_SIGNING_KEY}